version: '3'
services:
  node:
    build:
      context: ./back
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]  
  fastify:
    build:
      context: ./search_API
    ports:
      - "3030:3030"
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]    
  mongo:
    build:
      context: ./bdd
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  # frontend:
  #   build:
  #     context: ./front
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - node
volumes:
  mongo_data:
